version: "3.9"

services:
  bridge:
    image: ${BRIDGE_IMAGE:-chatwoot-linkedin-bridge:latest}
    environment:
      CHATWOOT_BASE_URL: ${CHATWOOT_BASE_URL}
      CHATWOOT_ACCOUNT_ID: ${CHATWOOT_ACCOUNT_ID}
      CHATWOOT_INBOX_ID: ${CHATWOOT_INBOX_ID}
      CHATWOOT_API_TOKEN: ${CHATWOOT_API_TOKEN}
      UNIPILE_BASE_URL: ${UNIPILE_BASE_URL}
      UNIPILE_API_KEY: ${UNIPILE_API_KEY}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      WEBHOOK_SECRET: ${WEBHOOK_SECRET}
      DEDUPE_TTL_SECONDS: ${DEDUPE_TTL_SECONDS:-120}
      REQUEST_TIMEOUT_SECONDS: ${REQUEST_TIMEOUT_SECONDS:-10}
      REQUEST_RETRIES: ${REQUEST_RETRIES:-2}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      UVICORN_WORKERS: ${UVICORN_WORKERS:-2}
    networks:
      - traefik
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8000/health')\""]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=${TRAEFIK_NETWORK:-network_public}"
        - "traefik.http.routers.bridge.rule=Host(`${BRIDGE_DOMAIN}`)"
        - "traefik.http.routers.bridge.entrypoints=websecure"
        - "traefik.http.routers.bridge.tls=true"
        - "traefik.http.routers.bridge.tls.certresolver=${TRAEFIK_CERT_RESOLVER:-letsencryptresolver}"
        - "traefik.http.services.bridge.loadbalancer.server.port=8000"

networks:
  traefik:
    external: true
    name: ${TRAEFIK_NETWORK:-network_public}
